CREATE SCHEMA `dwh` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
/**
  数据源
 */
-- DROP TABLE  IF EXISTS dwh.DATA_SOURCE_REGISTER;
CREATE TABLE IF NOT EXISTS dwh.DATA_SOURCE_REGISTER(
    ID BIGINT(64) PRIMARY KEY COMMENT '主键',
    SOURCE_NAME VARCHAR(200) NOT NULL COMMENT '数据源名称',
    SOURCE_TYPE VARCHAR(50) NOT NULL COMMENT '数据源名称',
    SOURCE_IP VARCHAR(15) NOT NULL COMMENT  '数据源IP',
    SOURCE_PORT VARCHAR(6) NOT NULL COMMENT '数据源端口',
    USER_NAME VARCHAR(200) NOT NULL COMMENT '账户名称',
    USER_PASSWORD VARCHAR(200) NOT NULL COMMENT '密码',
    INFORMATION_ID BIGINT(64) NOT NULL COMMENT '数据源信息主键',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_TIME DATETIME COMMENT '创建时间',
    CREATE_USER VARCHAR(64) COMMENT '创建人',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    UPDATE_USER VARCHAR(64) COMMENT '更新人'
    );
ALTER TABLE `dwh`.`DATA_SOURCE_REGISTER`
    ADD UNIQUE INDEX `uniqueDataSource` (`SOURCE_IP` ASC, `SOURCE_PORT` ASC, `SOURCE_NAME` ASC) VISIBLE;
, COMMENT = '数据源注册' ;

/**
  系统注册表
 */
-- DROP TABLE  IF EXISTS dwh.SYSTEM_REGISTER;
CREATE TABLE IF NOT EXISTS dwh.SYSTEM_REGISTER(
    ID BIGINT(64) PRIMARY KEY COMMENT '主键',
    SYSTEM_NAME VARCHAR(200) NOT NULL COMMENT '系统名称',
    WORK_PATH VARCHAR(200) NOT NULL COMMENT '工作路径',
    LOG_PATH VARCHAR(200) NOT NULL COMMENT  '日志路径',
    DEPLOY_PATH VARCHAR(200) NOT NULL COMMENT '部署路径',
    SYSTEM_IP VARCHAR(200) NOT NULL COMMENT '服务IP',
    SYSTEM_PORT VARCHAR(200) NOT NULL COMMENT '运行端口',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_TIME DATETIME COMMENT '创建时间',
    CREATE_USER VARCHAR(64) COMMENT '创建人',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    UPDATE_USER VARCHAR(64) COMMENT '更新人'
    )COMMENT = '系统注册';
/**
  功能注册
 */
-- DROP TABLE  IF EXISTS dwh.FUNCTION_REGISTER;
CREATE TABLE IF NOT EXISTS dwh.FUNCTION_REGISTER(
    ID  BIGINT(64)   PRIMARY KEY COMMENT '主键',
    FUNCTION_NAME VARCHAR(200) NOT NULL COMMENT '功能名称',
    FUNCTION_CODE VARCHAR(64) NOT NULL COMMENT '功能编码',
    SYSTEM_ID VARCHAR(64) NOT NULL COMMENT '系统主键',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_TIME DATETIME COMMENT '创建时间',
    CREATE_USER VARCHAR(64) COMMENT '创建人',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    UPDATE_USER VARCHAR(64) COMMENT '更新人'
    )COMMENT = '功能注册';
/**
  任务注册
 */
-- DROP TABLE  IF EXISTS dwh.TASK_REGISTER;
CREATE TABLE IF NOT EXISTS dwh.TASK_REGISTER(
    ID BIGINT(64) PRIMARY KEY COMMENT '主键',
    TASK_NAME VARCHAR(200) NOT NULL COMMENT '任务名称',
    TASK_CODE VARCHAR(64) NOT NULL COMMENT '任务编码',
    SYSTEM_ID VARCHAR(64) NOT NULL COMMENT '服务IP',
    FUNCTION_ID VARCHAR(64) NOT NULL COMMENT '功能主键',
    SOURCE_ID VARCHAR(64) NOT NULL COMMENT '数据源主键',
    SOURCE_TABLE VARCHAR(64) NOT NULL COMMENT '数据来源表',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_TIME DATETIME COMMENT '创建时间',
    CREATE_USER VARCHAR(64) COMMENT '创建人',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    UPDATE_USER VARCHAR(64) COMMENT '更新人'
    ) COMMENT = '任务注册';
