
server:
  port: 6066
  servlet:
    context-path: /dwh
springdoc:
  version: 1.0
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: api
      pathsToMatch: /api/**
    - group: openApi
      pathsToMatch: /openApi/**
      packagesToScan: com.dwh.bi.api
ds:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource: #数据库链接相关配置
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: admin
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      primary: master
      datasource:
        master:
          url: jdbc:mysql://ubuntu2004.wsl:3306/dwh?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
          username: root
          password: root
          init:
            schema: sql/createDwhDataBase.sql
            continue-on-error: true
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size:
            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
            public-key: #（非全局参数）设置即表示启用加密,底层会自动帮你配置相关的连接参数和filter。

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring:
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/dwh
#          username: root
#          password: root
#          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#        slave_1:
#          url: jdbc:mysql://10.0.105.38:3306/test_gb_adapter
#          username: root
#          password: 123qwe!@#
#          driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
