server:
  port: 6066
  servlet:
    context-path: /dwh
springdoc:
  version: 1.0
  swagger-ui:
    path: /doc.html
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: api
      pathsToMatch: /api/**
    - group: openApi
      pathToMatch: /openApi/**
      packagesToScan: com.dwh.bi

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://ubuntu2004.wsl:3306/dwh
          username: root
          password: root
#          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#        slave_1:
#          url: jdbc:mysql://10.0.105.38:3306/test_gb_adapter
#          username: root
#          password: 123qwe!@#
#          driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
